# mkdocs build -d ../docs

site_name: IBM Watson IoT Platform
nav:
  - 'Home': index.md
  - 'Application SDK':
    - 'Overview': application/index.md
    - 'Configuration': application/config.md
    - 'Device Commands': application/mqtt/commands.md
    - 'Device Events': application/mqtt/events.md
    - 'Device Status Updates': application/mqtt/status.md
    - 'Registry - Types': application/api/registry/types.md
    - 'Registry - Devices': application/api/registry/devices.md
    - 'Registry - Diagnostics': application/api/registry/diag.md
    - 'Device Management': application/api/mgmt.md
    - 'Last Event Cache': application/api/lec.md
    - 'Service Status': application/api/status.md
    - 'Usage Reports': application/api/usage.md
  - 'Device SDK':
    - 'Overview': device/index.md
    - 'Configuration': device/config.md
    - 'Managed Devices': device/managed.md
  - 'Gateway SDK':
    - 'Overview': gateway/index.md
    - 'Configuration': gateway/config.md
    - 'Managed Gateways': gateway/managed.md
  - 'Common Topics':
    - 'Custom Message Formats': custommsg.md
    - 'Exceptions': exceptions.md

theme: readthedocs

markdown_extensions:
  - toc:
      permalink: 
