# mkdocs build -d ../docs

site_name: IBM Watson IoT Platform
nav:
  - 'Home': index.md
  - 'Application SDK':
    - 'Overview': application/index.md
    - 'Configuration': application/config.md
  - 'Device SDK':
    - 'Overview': device/index.md
    - 'Configuration': device/config.md
    - 'Managed Devices': device/managed.md
  - 'Gateway SDK':
    - 'Gateway SDK Overview': gateway/index.md
    - 'GatewayConfiguration': gateway/config.md
    - 'Managed Gateways': gateway/managed.md
  - 'Common Topics':
    - 'Custom Message Formats': custommsg.md
    - 'Exceptions': exceptions.md

theme: readthedocs

markdown_extensions:
  - toc:
      permalink: 
